name: Monitor de Preços Automatizado

on:
  workflow_dispatch:          # Permite rodar manualmente pelo painel do GitHub
    inputs:
      loja:
        description: 'Selecione a loja:'
        required: true
        type: choice
        default: 'todas'
        options:
          - todas
          - centauro
          - nagumo
          - shibata

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install curl_cffi requests

      # ==========================================
      # CENTAURO
      # ==========================================
      - name: Rodar Monitor Centauro
        if: github.event_name != 'workflow_dispatch' || github.event.inputs.loja == 'todas' || github.event.inputs.loja == 'centauro'
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python centauro.py
        continue-on-error: true # Se der erro, não para a execução das outras lojas

      # ==========================================
      # NAGUMO
      # ==========================================
      - name: Rodar Monitor Nagumo
        if: github.event_name != 'workflow_dispatch' || github.event.inputs.loja == 'todas' || github.event.inputs.loja == 'nagumo'
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python nagumo.py
        continue-on-error: true

      # ==========================================
      # SHIBATA
      # ==========================================
      - name: Rodar Monitor Shibata
        if: github.event_name != 'workflow_dispatch' || github.event.inputs.loja == 'todas' || github.event.inputs.loja == 'shibata'
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python shibata.py
        continue-on-error: true
